version: "3"
services:
  api:
    build: .
    ports:
      - 3004:3004
    volumes:
      - ./api:/app/api
      - ./app.js:/app/app.js
      - ./server.js:/app/server.js
    depends_on:
      - redis
      - mongo
  redis:
    image: "redis:alpine"
    container_name: collabz_redis
    expose:
      - 6379
  mongo:
    image: "mongo"
    volumes:
      - ./dump:/data/db
